[package]
name = "message_parser_macros"
version = "0.1.0"
edition = "2021"

[dependencies]
darling = "0.20.10"
proc-macro2 = "1.0.86"
quote = "1.0.37"
syn = "2.0.77"

[lib]
name = "message_parser_macros"
path = "src/lib.rs"
proc-macro = true
